<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <NoWarn>$(NoWarn);CA1416;CS8602;CS8604</NoWarn>
  </PropertyGroup>

  <!-- Debug 模式不使用管理员权限，Release 模式使用 -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
    
    <PackageReference Include="Clipper2" Version="1.4.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="**\*.xaml" Exclude="bin\**;obj\**" />
  </ItemGroup>

  <ItemGroup>
    <!-- 将 models 文件夹嵌入为资源 -->
    <EmbeddedResource Include="models\**\*" />
  </ItemGroup>

  <ItemGroup>
    <!-- 排除 test_simple 目录中的所有 .cs 文件 -->
    <Compile Remove="test_simple\**\*.cs" />
    <Compile Remove="resource\**\*.cs" />
    <None Include="test_simple\**\*.cs" />
    <None Include="OcrEngine_CUDA.cs" />
    <Compile Remove="OcrEngine_CUDA.cs" />
    <!-- 排除 test 目录 -->
    <Compile Remove="test\**\*" />
    <None Remove="test\**\*" />
    <Content Remove="test\**\*" />
    <EmbeddedResource Remove="test\**\*" />
    
    <!-- 排除 UE4.27.2 目录 -->
    <Compile Remove="UE4.27.2\**\*" />
    <None Remove="UE4.27.2\**\*" />
    <Content Remove="UE4.27.2\**\*" />
    <EmbeddedResource Remove="UE4.27.2\**\*" />
    
    <!-- 排除 Dumper-7 目录 -->
    <Compile Remove="Dumper-7\**\*" />
    <None Remove="Dumper-7\**\*" />
    <Content Remove="Dumper-7\**\*" />
    <EmbeddedResource Remove="Dumper-7\**\*" />
    
    <!-- 排除 ida-pro-mcp 目录 -->
    <Compile Remove="ida-pro-mcp\**\*" />
    <None Remove="ida-pro-mcp\**\*" />
    <Content Remove="ida-pro-mcp\**\*" />
    <EmbeddedResource Remove="ida-pro-mcp\**\*" />
    
    <!-- 排除 cheat-engine-server-python 目录 -->
    <Compile Remove="cheat-engine-server-python\**\*" />
    <None Remove="cheat-engine-server-python\**\*" />
    <Content Remove="cheat-engine-server-python\**\*" />
    <EmbeddedResource Remove="cheat-engine-server-python\**\*" />
  </ItemGroup>

</Project>